name: Update MyHosts in Scoop Bucket

on:
  release:
    types: [published]
  workflow_dispatch: # Allows manual triggering

jobs:
  update-scoop:
    uses: ropean/my-github-actions/.github/workflows/update-scoop.yml@main
    with:
      app_name: 'myhosts'
      exe_name: 'MyHosts.exe'
      scoop_bucket_repo: 'ropean/scoop-ropean'
      source_repo: ${{ github.repository }}
      description: 'Hosts file editor utility for Windows'
      homepage: 'https://github.com/ropean/MyHosts'
      license_identifier: 'MIT'
      license_url: 'https://github.com/ropean/MyHosts/blob/main/LICENSE'
      bin_name: 'MyHosts.exe'
      shortcut_name: 'MyHosts'
      shortcut_description: 'Hosts file editor'
      notes: 'MyHosts is a utility that helps you edit and manage the Windows hosts file for network configuration and blocking.'
    secrets: inherit # This passes all secrets from the calling repo
