name: Update MyHosts in Scoop Bucket

on:
  release:
    types: [published, released, created]
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v2.1.3, etc.
  # workflow_dispatch: # Allows manual triggering for testing

jobs:
  update-scoop:
    # Only run if it's a release event OR a tag push (avoid duplicate runs)
    if: github.event_name == 'release' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    uses: ropean/my-github-actions/.github/workflows/update-scoop.yml@main
    with:
      app_name: 'myhosts'
      exe_name: 'MyHosts.exe'
      scoop_bucket_repo: 'ropean/scoop-ropean'
      source_repo: ${{ github.repository }}
      description: 'Hosts file editor utility for Windows'
      homepage: 'https://github.com/ropean/MyHosts'
      license_identifier: 'MIT'
      license_url: 'https://github.com/ropean/MyHosts/blob/main/LICENSE'
      bin_name: 'MyHosts.exe'
      shortcut_name: 'MyHosts'
      shortcut_description: 'Hosts file editor'
      notes: 'MyHosts is a utility that helps you edit and manage the Windows hosts file for network configuration and blocking.'
    # No secrets section - the reusable workflow uses its own repo secrets
    # secrets: inherit
